apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms
  namespace: default
  labels:
    app: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms
  template:
    metadata:
      labels:
        app: oms
    spec:
      containers:
      - name: oms
        image: solicitousabhi/oms
