apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ssc600
  name: ssc600
spec:
  containers:
  - image: solicitousabhi/ssc600
    name: whmi
    env:
      - name: ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS
        value: 'true'
    ports:
      - containerPort: 5004
        name: https
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  imagePullSecrets:
  - name: regcred
status: {}

-----------------------

apiVersion: v1
kind: Service
metadata:
  name: ssc600
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ssc600
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004

-----------------------



